version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway
      target: builder
    command: air
    env_file:
      - ./api-gateway/dev.env
    volumes:
      - ./api-gateway:/go/src/api-gateway
    ports:
      - "8000:8000"
    networks:
      - online-test

  auth-service:
    build:
      context: ./auth-service
      target: builder
    command: air
    env_file:
      - ./auth-service/dev.env
    volumes:
      - ./auth-service:/go/src/auth-service
    ports:
      - "5000:5000"
    networks:
      - online-test

  postgres:
    image: postgres:13.8
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/postgresql:/var/lib/postgresql/data
      - ./db-data/docker-entrypoint:/docker-entrypoint-initdb.d
    networks:
      - online-test

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    networks:
      - online-test

networks:
  online-test: